# Generated by Django 4.0 on 2022-01-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0003_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user_id',
            new_name='user',
        ),
    ]
