# Generated by Django 4.0 on 2022-01-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_rename_user_id_contributor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='author_user_id',
            new_name='author_user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
